package sg.com.trekstorageauthentication.service.ble

enum class BleResponseType {
    REGISTER_PASSWORD_SUCCESS,
    REGISTER_PASSWORD_FAIL,
    RESET_PASSWORD_SUCCESS,
    RESET_PASSWORD_FAIL,
    UNLOCK_PASSWORD_SUCCESS,
    UNLOCK_PASSWORD_FAIL,
    PASSWORD_STATUS,
    LOG_OUT_SUCCESS,
    LOG_OUT_FAIL
}